### ISSUE TITLE
数据初始化问题

### ISSUE THREAD

**Issue by luoyueyi** [thunlp/AMNRE#1]
您好，我在调试代码时，使用CNN/src/init.py 初始化数据，发现无法运行。
1、constant.py 文件中变量 SenLen=[70,85] #Max Sentence Length for Position Embedding 是否正确
2、 CNN/src/init.py 文件中  load_vo2()无法执行，缺少数据文件
3、 CNN/src/init.py 文件中
 函数
 def augment(self):
        L=len(self.instances)
        for i in range(0,L):
            if self.instances[i].r!=0:
                for t in range(0,AugTimes):
                    self.instances.append(self.instances[i])
AugTimes没有定义

**Comment by Bakser** [comment]
您好，感谢您指出问题。

1. 这里参数是正确的，分别是英文和中文的句子长度。init.py上传了一个没有做此修改的过时版本，已经改正。

2. load_vo2函数是读取预处理的wordvec的pickle文件，加速读入。第一次运行应当在load_init中使用load_vocab函数，将读取文本格式的wordvec文件并处理成pickle格式。已经做了对应修改。

3. 这个函数用于data augmentation，后来的模型中发现并不需要这个操作，故删去了对应参数，最新的init.py里也删去了调用。

最新的commit里做了init,py的修改，请重新pull一下。很抱歉由于经验不足init.py写的比较混乱也比较耗时。如果想要测试模型的话直接下载npy数据就好。
