### ISSUE TITLE
没有entity2id.txt文件

### ISSUE THREAD

**Issue by zhangluoli** [thunlp/AMNRE#10]
![04a984e5eb864b7ed691f386b22ea33](https://user-images.githubusercontent.com/52224308/165766995-331dd25a-09f4-4b36-b56c-7f1d57a33e6a.png)是有那个文件的，但是为什么会报错

**Comment by Bakser** [comment]
可能是相对路径不准确，请确定运行程序的目录的`../Data/entity2id.txt`这个相对路径正确指向该文件
