### ISSUE TITLE
数据集失效

### ISSUE THREAD

**Issue by 1250658183** [thunlp/AMNRE#11]
作者您好，虽然这篇工作已经发表了许久，但是至今仍给我了很多启发！在复现工作的过程中，我发现redeme中附的处理好的数据的链接已经失效，并且我自己执行处理程序，总是会卡在 np.save(dataPath+Tag+"epEn.npy",np.array(ep_en)) 代码行。我想请问一下作者，目前还能重新上传一版已处理好的数据吗？

任何可能的帮助都将万分感谢！

**Comment by Bakser** [comment]
您好，感谢您的关注，已经重新上传了数据。
