### ISSUE TITLE
关于测试数据和attention

### ISSUE THREAD

**Issue by luoyueyi** [thunlp/AMNRE#2]
CNN/train.py中调用 test(testSet,"Test",e)函数时，报Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #3 'index' 错误。根据我的分析，在训练数据和测试时，re_mask的维度是不一致的。
我一直有一个疑问，在使用 language-individual attention时，网络训练时，关系r是已知的，但是到测试时关系r是未知的，在调用

```
class MonoRE(nn.Module):
    def __init__(self):
        super(MonoRE,self).__init__()
        self.relation_emb=nn.Embedding(dimR,Encodered_dim)
        self.dropout=nn.Dropout(p=Att_dropout)
        #self.softmax=nn.Softmax()
        #self.logsoftmax=nn.LogSoftmax()
        self.M=nn.Linear(Encodered_dim,dimR)
    def forward(self,inp,r,l,re_mask):
        NumRe=r.size(0)
        NumIn=l.size(0)
        print(r.size())
        relation=self.relation_emb(r)
        attn=torch.sum(relation*inp,2)
        p=Variable(torch.cuda.FloatTensor(NumIn,NumRe).fill_(0.0))
        L=0
        R_vec=Variable(torch.cuda.FloatTensor(NumIn,NumRe,Encodered_dim).fill_(0.0))
        S=Variable(torch.cuda.FloatTensor(NumIn,NumRe,Encodered_dim).fill_(0.0))
        for i in range(0,NumIn):
            R=L+l[i].item()          
            if R>L:
                Att=F.softmax(attn[:,L:R],1)
                S[i]=self.dropout(torch.matmul(Att,inp[L:R]))
                R_vec[i]=relation[:,L,:]
            L=R
        p_n=F.log_softmax((self.M(S)+torch.sum(R_vec*S,2).view(NumIn,NumRe,1)),2).view(NumIn,NumRe,dimR)
        return p_n[re_mask].view(NumIn,NumRe)
```

时，这个r的含义是什么？
谢谢解释。

**Comment by huaiwen** [comment]
我看到文章中有写 测试的时候的 query 哪里来的。
原文：
In the training phase, p(r|T) is computed using the labeled relations as the attention queries. In the test phase, we need to use each possible relation as attention queries to compute p(r|T ) for relation prediction since the relations are unknown in advance.

**Comment by Bakser** [comment]
我测试了一下，并没有遇到这个问题。从错误提示来看应当是某个地方传入的参数没有转换到GPU上。请检查一下有没有对dataset.py或者train.py做过修改，以及运行环境。
关于测试时r的问题，在论文3.4节我们讲过，测试阶段应当对每种关系都计算一遍，而逐个进行计算太费时间，因此可以利用矩阵运算的性质，将所有关系作为一个矩阵一次进行attention计算，所以这里的维度是没有问题的。
