### ISSUE TITLE
try to reproduce the results 

### ISSUE THREAD

**Issue by Impavidity** [thunlp/AMNRE#6]
Hey, I try to run `CNN/train.py` and finish the training. How can I get the prediction results and run the then `draw.py`.

**Comment by Bakser** [comment]
As the setting in the original codes (`OutRes=True`), you should have gotten two files like `AMNRE_CNN_label_[Time].npy` and `AMNRE_CNN_pred_[Time].npy` in the running path. You can just feed them into the `draw.py`.
