### ISSUE TITLE
Bug in function Orth_con in models.py 

### ISSUE THREAD

**Issue by yanfan0531** [thunlp/AMNRE#8]
In models.py, the code from line 193 to 196 is as follows:
```
share_en,share_zh=self.share_encoder(wordsEn,pos1En,pos2En,wordsZh,pos1Zh,pos2Zh)
mono_en,mono_zh=self.monoRE.encoder(wordsEn,pos1En,pos2En,wordsZh,pos1Zh,pos2Zh)
share=torch.cat((share_en,share_zh),0)
mono=torch.cat((share_en,share_zh),0)
```
where Tensor mono_en and mono_zh are not concatenated to Tensor mono. I think there is a bug where line 196 should be:
`mono=torch.cat((mono_en,mono_zh),0)`

The code from line 197 to 200:
```
share-=torch.mean(share,0)
mono-=torch.mean(share,0)
share=F.normalize(share,2,1)
mono=F.normalize(share,2,1)
```
obviously it is also a typo where the input of line 198 and 200 should be Tensor mono instead of Tensor share.

**Comment by Bakser** [comment]
Fixed. Thanks for pointing out it! These codes are for an ablation study (using the same dimension but only shared attention) and I forget to change it while releasing.
